name : first workflow 
on :
  workflow_dispatch :
    inputs :
      environment :
        description : " enter environment name "
        required : true
        default : "staging "
      branch :
        desciption : "enter branch name "
        required : true
        default : "main"
      deployed_by :
        description : "enter name of the person who deployed "
        required : true
        default : "devops"
        
  schedule : 
    - cron : "0 9 * * *"
  pull_request : 
jobs :
  hello :
    runs-on : ubuntu-latest
    steps :
      - name : say-hello
        run : echo " ${{ inputs.branch }}"

      - name : print working directory 
        run : echo  "${{ inputs.environment }} "

      - name : print host related details 
        run : echo "${{ inputs.deployed_by }}"

      - name : print os related details
        run : cat /etc/os-release 


    
