name : test needs
on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        default: "World"
        type: string
      environment:
        description: 'Environment to deploy to'
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod    
      yes:
        description: 'Are you sure you want to deploy?'
        required: true
        default: "no"
        type: string
        options:
          - yes
          - no    

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "build stage"
      - run: echo "${{ inputs.environment }}"
      - run: echo "${{ inputs.yes }}"

  test :
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - run: echo "test stage"
  lint :
    runs-on: ubuntu-latest
    needs: test
    steps: 
      - run: echo "lint stage"
  deploy :
    runs-on: ubuntu-latest
    needs: 
      - build 
      - lint
      - test
    steps: 
      - run: echo "deploy stage"        
