name: start learnig github action 
on :
  push:
  workflow_dispatch:

jobs :
  condition-lab:
    runs-on: ubuntu-latest

    steps:      
      - name : run when event is pull request
        if: github.event_name == 'pull_request'
        run : echo " this is always run"

      - name : run when i pushed into main branch 
        if : github.ref == 'refs/heads/main'
        run : |
         echo 'runs when i pushed into main branch deployemnt started '
         sudo apt install node.js -y 
         sudo apt install npm -y 
         npm install 
         npm run start
  
        
      